const APPOINTMENT = {
  STATUSES: {
    UNAPPROVED: "UNAPPROVED",
    APPROVED: "APPROVED",
    REJECTED: "REJECTED",
    CLOSED: "CLOSED",
  },
  TYPES: {
    VIRTUAL_CONSULTATION: "VIRTUAL_CONSULTATION",
    ONSITE_CONSULTATION: "ONSITE_CONSULTATION",
    ONSITE_TESTS: "ONSITE_TESTS",
  },
};

const USER = {
  ACCOUNT_TYPES: {
    PROFESSIONAL: "PROFESSIONAL",
    INSTITUTION: "INSTITUTION",
    PATIENT: "PATIENT",
    ADMIN: "ADMIN",
  },
};

const PROFILE_PICTURE_FORMATS = [
  "image/jpg",
  "image/jpeg",
  "image/png",
  "image/gif",
];

const ALLOWED_VIDEO_FILE_TYPES = ["video/mp4", "video/webm"];

const TEST_RESET_CODE = "345656";

const ALLOWED_FILE_TYPES = ["doc", "docx", "pdf"];

module.exports = {
  ALLOWED_FILE_TYPES,
  ALLOWED_VIDEO_FILE_TYPES,
  APPOINTMENT,
  PROFILE_PICTURE_FORMATS,
  TEST_RESET_CODE,
  USER,
};
